spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    #url of the mysql database
    url: jdbc:mysql://localhost:3306/usermanagementdb?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
server:
  #port number of the service
  port: 8200